"""add account model, change money model to transaction model and add account.id.

Revision ID: 3a46ddbcd3b6
Revises: 4f55ce7eafdc
Create Date: 2015-11-07 21:34:23.234661

"""

# revision identifiers, used by Alembic.
revision = '3a46ddbcd3b6'
down_revision = '4f55ce7eafdc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=254), nullable=True),
    sa.Column('lastname', sa.String(length=254), nullable=True),
    sa.Column('username', sa.String(length=254), nullable=True),
    sa.Column('password', sa.String(length=254), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('transaction_type', sa.String(length=64), nullable=True),
    sa.Column('catergory_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['catergory_id'], ['category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('money')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('money',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('money_type', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('catergory_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['catergory_id'], [u'category.id'], name=u'money_ibfk_1', ondelete=u'SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('transaction')
    op.drop_table('account')
    ### end Alembic commands ###
