"""remove coins table

Revision ID: 4dd433b09fa6
Revises: 797ee5c4cfc
Create Date: 2015-11-05 16:48:14.837396

"""

# revision identifiers, used by Alembic.
revision = '4dd433b09fa6'
down_revision = '797ee5c4cfc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coin')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('money_type', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('catergory_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['catergory_id'], [u'category.id'], name=u'coin_ibfk_1', ondelete=u'SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
