"""change category.typype from integer to string(64)

Revision ID: 4f55ce7eafdc
Revises: 4dd433b09fa6
Create Date: 2015-11-05 17:44:17.146765

"""

# revision identifiers, used by Alembic.
revision = '4f55ce7eafdc'
down_revision = '4dd433b09fa6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'category_type',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=64),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'category_type',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    ### end Alembic commands ###
