"""add account_id to categories

Revision ID: 5257c370c8d3
Revises: 3a46ddbcd3b6
Create Date: 2015-11-09 19:11:41.509682

"""

# revision identifiers, used by Alembic.
revision = '5257c370c8d3'
down_revision = '3a46ddbcd3b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'account', ['account_id'], ['id'], ondelete='SET NULL')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'account_id')
    ### end Alembic commands ###
