"""initial commit

Revision ID: 570d3ae16251
Revises: None
Create Date: 2015-11-05 16:42:51.747130

"""

# revision identifiers, used by Alembic.
revision = '570d3ae16251'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('category_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('money',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('money_type', sa.String(length=64), nullable=True),
    sa.Column('catergory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catergory_id'], ['category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('money')
    op.drop_table('category')
    ### end Alembic commands ###
