"""add coins table

Revision ID: 797ee5c4cfc
Revises: 570d3ae16251
Create Date: 2015-11-05 16:46:36.529644

"""

# revision identifiers, used by Alembic.
revision = '797ee5c4cfc'
down_revision = '570d3ae16251'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('money_type', sa.String(length=64), nullable=True),
    sa.Column('catergory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catergory_id'], ['category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coin')
    ### end Alembic commands ###
